services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: game_monitoring
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped
