export { default as DashboardIcon } from "./DashboardIcon";
export { default as SettingsIcon } from "./SettingsIcon";
export { default as OpenSidebar } from "./OpenSidebar";
export { default as CloseSidebar } from "./CloseSidebar";
export { default as PlusIcon } from "./PlusIcon";
export { default as CloseModalIcon } from "./CloseModalIcon";
export { default as RightArrowIcon } from "./RightArrowIcon";
export { default as ClipboardIcon } from "./ClipboardIcon";
export { default as SuccessIcon } from "./SuccessIcon";
